# Makefile for COMP20003, catc-up workshop
# july, 2011

all: mainLen 

mainLen: main.o merge.o queue.o util.o smalloc.o Makefile 
	$(CC) -o mergeArray main.o merge.o queue.o util.o smalloc.o


CC=gcc
